# Generated by Django 2.1.7 on 2019-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
